<?php 

// include.php  - Handles options and common functions for subscribe2
// DO NOT EDIT THIS FILE AS IT IS SET BY THE OPTIONS PAGE


// remind_email
//
if(empty($this->subscribe2_options['remind_email'])) {
    $this->subscribe2_options['remind_email'] = "This email address was subscribed for notifications at BLOGNAME (BLOGLINK) but the subscription remains incomplete.\n\nIf you wish to complete your subscription please click on the link below:\n\nLINK\n\nIf you do not wish to complete your subscription please ignore this email and your address will be removed from our database.\n\nRegards,\nMYNAME";
}
// autosub : automatically subscribes users to newly created categories

if (empty($this->subscribe2_options['autosub'])) { 
	$this->subscribe2_options['autosub'] = "no"; 
}

// excluded_cats : category IDs that will not generate notifications
// value : category IDs

if (empty($this->subscribe2_options['exclude'])) {
	$this->subscribe2_options['exclude'] = "";
}

// sender  : who the emails come from. 
if (empty($this->subscribe2_options['sender'])) {
	$this->subscribe2_options['sender'] = "author";
}

// reg_override : allow registered users to subscribed to excluded cats
if (empty($this->subscribe2_options['reg_override'])) {
	$this->subscribe2_options['reg_override'] = 1;
}

if (empty($this->subscribe2_options['show_button'])) {
	$this->subscribe2_options['show_button'] = 1;
}

if (empty($this->subscribe2_options['barred'])) {
	$this->subscribe2_options['barred'] = '';
}

if (empty($this->subscribe2_options['mailtext'])) {
	$this->subscribe2_options['mailtext'] = "BLOGNAME has posted a new item, 'TITLE'\r\nPOST\r\nYou may view the latest post at\r\nPERMALINK\r\nYou received this e-mail because you asked to be notified when new updates are posted.\r\nBest regards,\r\nMYNAME\r\nEMAIL";
}

if (empty($this->subscribe2_options['confirm_email'])) {
	$this->subscribe2_options['confirm_email'] = "In order to confirm your request for BLOGNAME, please click on the link below:\n\nLINK\n\nIf you did not request this, please feel free to disregard this notice!\n\nThank you,\nMYNAME.";
}

if (empty($this->subscribe2_options['remind_email'])) {
	$this->subscribe2_options['remind_email'] = "This email address was subscribed for notifications at BLOGNAME (BLOGLINK) but the subscription remains incomplete.\n\nIf you wish to complete your subscription please click on the link below:\n\nLINK\n\nIf you do not wish to complete your subscription please ignore this email and your address will be removed from our database.\n\nRegards,\nMYNAME";
}

if (empty( $this->subscribe2_options['autoformat'] ) ) {
    $this->subscribe2_options['autoformat'] = "text";
}
?>